"""A bad target must never connect; a drift failure must clean up only its DB."""

import os
import subprocess
import sys
from pathlib import Path

import pytest
from sqlalchemy import text

OPS = Path(__file__).resolve().parents[2] / "database" / "ops"
sys.path.insert(0, str(OPS))


@pytest.mark.parametrize(
    "raw",
    [
        "",
        "postgresql://SYNTHETIC_SECRET@remote.invalid/perennial_test",
        "postgresql://SYNTHETIC_SECRET@127.0.0.1/production",
        "postgresql://SYNTHETIC_SECRET@127.0.0.1/perennial_test?hostaddr=8.8.8.8",
    ],
)
def test_migration_gate_rejects_unsafe_target_without_connecting(raw, monkeypatch):
    import quality_gate

    def forbidden(*args, **kwargs):
        pytest.fail("unsafe target reached engine creation")

    monkeypatch.setattr(quality_gate, "create_engine", forbidden)
    with pytest.raises(ValueError):
        quality_gate.check_migrations(raw)


def test_migration_gate_cli_fails_closed_without_url():
    env = dict(os.environ)
    env.pop("TEST_DATABASE_URL", None)
    result = subprocess.run(
        [sys.executable, str(OPS / "quality_gate.py")],
        env=env,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 1
    assert "Migration quality gate failed (ValueError)" in result.stderr
    assert "Traceback" not in result.stderr


@pytest.mark.db
def test_drift_is_rejected_and_disposable_database_is_removed(engine, monkeypatch):
    import quality_gate
    from alembic.util.exc import AutogenerateDiffsDetected

    def database_names():
        with engine.connect() as conn:
            return set(conn.execute(text("SELECT datname FROM pg_database")).scalars())

    before = database_names()
    real_check = quality_gate.command.check
    drift_detected = []

    def inject_schema_drift(cfg):
        conn = cfg.attributes["connection"]
        conn.execute(
            text("ALTER TABLE perennial.securities ADD COLUMN unexpected_column text")
        )
        conn.commit()
        try:
            real_check(cfg)
        except AutogenerateDiffsDetected:
            drift_detected.append(True)
            raise

    monkeypatch.setattr(quality_gate.command, "check", inject_schema_drift)
    with pytest.raises(AutogenerateDiffsDetected):
        quality_gate.check_migrations(engine.url.render_as_string(hide_password=False))
    assert drift_detected == [True]
    assert database_names() == before
    with engine.connect() as conn:
        assert (
            conn.execute(text("SELECT count(*) FROM perennial.securities")).scalar_one()
            == 0
        )
